-- At least 5 analytical SQL queries + record count validation
-- Target schema: RETAIL_ANALYTICS_DB.CURATED

USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA CURATED;

-- 1) Top 10 products by net revenue
SELECT
  PRODUCT_ID,
  PRODUCT_NAME,
  SUM(NET_AMOUNT) AS NET_REVENUE
FROM SALES_ENRICHED
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY NET_REVENUE DESC
LIMIT 10;

-- 2) Revenue by category and month
SELECT
  ORDER_MONTH,
  CATEGORY,
  NET_REVENUE,
  TOTAL_UNITS_SOLD
FROM MONTHLY_SALES_SUMMARY
ORDER BY ORDER_MONTH, CATEGORY;

-- 3) Customer lifetime value (top 10)
SELECT
  CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  ROUND(SUM(NET_AMOUNT), 2) AS LIFETIME_VALUE,
  COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM SALES_ENRICHED
GROUP BY CUSTOMER_ID, FIRST_NAME, LAST_NAME
ORDER BY LIFETIME_VALUE DESC
LIMIT 10;

-- 4) Average discount by payment method
SELECT
  PAYMENT_METHOD,
  ROUND(AVG(DISCOUNT_PCT), 2) AS AVG_DISCOUNT_PCT,
  ROUND(SUM(NET_AMOUNT), 2) AS NET_REVENUE
FROM SALES_ENRICHED
GROUP BY PAYMENT_METHOD
ORDER BY NET_REVENUE DESC;

-- 5) Return and cancellation rates by category
SELECT
  CATEGORY,
  COUNT(*) AS TOTAL_ROWS,
  SUM(CASE WHEN ORDER_STATUS = 'Returned' THEN 1 ELSE 0 END) AS RETURNED_ROWS,
  SUM(CASE WHEN ORDER_STATUS = 'Cancelled' THEN 1 ELSE 0 END) AS CANCELLED_ROWS,
  ROUND(100.0 * SUM(CASE WHEN ORDER_STATUS = 'Returned' THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS RETURN_RATE_PCT,
  ROUND(100.0 * SUM(CASE WHEN ORDER_STATUS = 'Cancelled' THEN 1 ELSE 0 END) / NULLIF(COUNT(*), 0), 2) AS CANCELLATION_RATE_PCT
FROM SALES_ENRICHED
GROUP BY CATEGORY
ORDER BY RETURN_RATE_PCT DESC;

-- Validation: source-to-target counts
SELECT 'ORDERS_CURATED' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM ORDERS_CURATED
UNION ALL
SELECT 'PRODUCTS_CURATED' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM PRODUCTS_CURATED
UNION ALL
SELECT 'CUSTOMERS_CURATED' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM CUSTOMERS_CURATED
UNION ALL
SELECT 'SALES_ENRICHED' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM SALES_ENRICHED
UNION ALL
SELECT 'MONTHLY_SALES_SUMMARY' AS TABLE_NAME, COUNT(*) AS RECORD_COUNT FROM MONTHLY_SALES_SUMMARY;
