-- Snowflake DDL for querying Apache Iceberg tables registered in AWS Glue.
-- This replaces the external-stage COPY INTO approach.

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS RETAIL_ANALYTICS_DB;
CREATE SCHEMA IF NOT EXISTS RETAIL_ANALYTICS_DB.CURATED;

USE ROLE ACCOUNTADMIN;

-- One-time setup for direct Iceberg table access.
-- Update ARNs/account values before running in your environment.
-- 1) External volume points Snowflake to the S3 Iceberg warehouse location.
CREATE OR REPLACE EXTERNAL VOLUME RETAIL_ICEBERG_EXT_VOL
  STORAGE_LOCATIONS = (
    (
      NAME = 'PRIMARY_S3'
      STORAGE_PROVIDER = 'S3'
      STORAGE_BASE_URL = 's3://test-bucket-484056256290-us-east-1-an/iceberg/'
      STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::484056256290:role/SnowflakeIceBerg'
    )
  );

DESC EXTERNAL VOLUME RETAIL_ICEBERG_EXT_VOL;

-- 2) Catalog integration connects Snowflake to AWS Glue's Iceberg metadata.
CREATE OR REPLACE CATALOG INTEGRATION GLUE_RETAIL_CATALOG_INT
  CATALOG_SOURCE = GLUE
  TABLE_FORMAT = ICEBERG
  GLUE_AWS_ROLE_ARN = 'arn:aws:iam::484056256290:role/SnowflakeIceBerg'
  GLUE_CATALOG_ID = '484056256290'
  ENABLED = TRUE;

DESC CATALOG INTEGRATION GLUE_RETAIL_CATALOG_INT;

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA CURATED;

-- Register Iceberg tables from Glue into Snowflake.
-- The table names below keep compatibility with existing analytics SQL.
CREATE OR REPLACE ICEBERG TABLE ORDERS_CURATED
  EXTERNAL_VOLUME = 'RETAIL_ICEBERG_EXT_VOL'
  CATALOG = 'GLUE_RETAIL_CATALOG_INT'
  CATALOG_NAMESPACE = 'iceberg_catalog_db'
  CATALOG_TABLE_NAME = 'orders'
  AUTO_REFRESH = TRUE;

CREATE OR REPLACE ICEBERG TABLE PRODUCTS_CURATED
  EXTERNAL_VOLUME = 'RETAIL_ICEBERG_EXT_VOL'
  CATALOG = 'GLUE_RETAIL_CATALOG_INT'
  CATALOG_NAMESPACE = 'iceberg_catalog_db'
  CATALOG_TABLE_NAME = 'products'
  AUTO_REFRESH = TRUE;

CREATE OR REPLACE ICEBERG TABLE CUSTOMERS_CURATED
  EXTERNAL_VOLUME = 'RETAIL_ICEBERG_EXT_VOL'
  CATALOG = 'GLUE_RETAIL_CATALOG_INT'
  CATALOG_NAMESPACE = 'iceberg_catalog_db'
  CATALOG_TABLE_NAME = 'customers'
  AUTO_REFRESH = TRUE;

CREATE OR REPLACE ICEBERG TABLE SALES_ENRICHED
  EXTERNAL_VOLUME = 'RETAIL_ICEBERG_EXT_VOL'
  CATALOG = 'GLUE_RETAIL_CATALOG_INT'
  CATALOG_NAMESPACE = 'iceberg_catalog_db'
  CATALOG_TABLE_NAME = 'sales_enriched'
  AUTO_REFRESH = TRUE;

CREATE OR REPLACE ICEBERG TABLE MONTHLY_SALES_SUMMARY
  EXTERNAL_VOLUME = 'RETAIL_ICEBERG_EXT_VOL'
  CATALOG = 'GLUE_RETAIL_CATALOG_INT'
  CATALOG_NAMESPACE = 'iceberg_catalog_db'
  CATALOG_TABLE_NAME = 'monthly_sales_summary'
  AUTO_REFRESH = TRUE;

-- Optional quick checks
SHOW ICEBERG TABLES IN SCHEMA RETAIL_ANALYTICS_DB.CURATED;
SELECT COUNT(*) AS ORDERS_CURATED_ROWS FROM ORDERS_CURATED;
