-- Snowflake DDL and load script for curated retail data
-- Update placeholders in angle brackets before running.

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS RETAIL_ANALYTICS_DB;
USE DATABASE RETAIL_ANALYTICS_DB;

CREATE SCHEMA IF NOT EXISTS CURATED;
USE SCHEMA CURATED;

CREATE OR REPLACE FILE FORMAT PARQUET_FF
  TYPE = PARQUET;




USE ROLE ACCOUNTADMIN;

-- One-time setup: run this block only when first creating the integration.
-- Re-running CREATE OR REPLACE can rotate integration metadata and invalidate
-- the AWS trust relationship until trust policy is updated again.
--
-- CREATE OR REPLACE STORAGE INTEGRATION S3_RETAIL_INT
-- TYPE = EXTERNAL_STAGE
-- STORAGE_PROVIDER = S3
-- ENABLED = TRUE
-- STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::484056256290:role/SnowflakeIceBerg'
-- STORAGE_ALLOWED_LOCATIONS = ('s3://test-bucket-484056256290-us-east-1-an/snowflake_exports/');

DESC INTEGRATION S3_RETAIL_INT;

USE ROLE SYSADMIN;
USE DATABASE RETAIL_ANALYTICS_DB;
USE SCHEMA CURATED;

CREATE OR REPLACE STAGE CURATED_S3_STAGE
  URL = 's3://test-bucket-484056256290-us-east-1-an/snowflake_exports/'
  STORAGE_INTEGRATION = S3_RETAIL_INT
  FILE_FORMAT = PARQUET_FF;

-- List files in the curated S3 stage to verify connectivity and contents
LIST @CURATED_S3_STAGE;
-- Curated orders table
CREATE OR REPLACE TABLE ORDERS_CURATED (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  PRODUCT_ID STRING,
  ORDER_DATE DATE,
  SHIP_DATE DATE,
  QUANTITY NUMBER,
  UNIT_PRICE FLOAT,
  DISCOUNT_PCT FLOAT,
  TOTAL_AMOUNT FLOAT,
  PAYMENT_METHOD STRING,
  ORDER_STATUS STRING
);

-- Curated products table
CREATE OR REPLACE TABLE PRODUCTS_CURATED (
  PRODUCT_ID STRING,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  BRAND STRING,
  PRICE FLOAT,
  COST FLOAT,
  STOCK_QUANTITY NUMBER,
  WEIGHT_KG FLOAT,
  CREATED_DATE DATE,
  IS_ACTIVE BOOLEAN
);

-- Curated customers table
CREATE OR REPLACE TABLE CUSTOMERS_CURATED (
  CUSTOMER_ID NUMBER,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  PHONE STRING,
  SIGNUP_DATE DATE,
  COUNTRY STRING,
  STATE STRING,
  POSTAL_CODE STRING,
  IS_ACTIVE BOOLEAN,
  LOYALTY_POINTS NUMBER
);

-- Curated enriched sales table
CREATE OR REPLACE TABLE SALES_ENRICHED (
  ORDER_ID STRING,
  ORDER_DATE DATE,
  SHIP_DATE DATE,
  CUSTOMER_ID STRING,
  FIRST_NAME STRING,
  LAST_NAME STRING,
  EMAIL STRING,
  COUNTRY STRING,
  STATE STRING,
  PRODUCT_ID STRING,
  PRODUCT_NAME STRING,
  CATEGORY STRING,
  BRAND STRING,
  QUANTITY NUMBER,
  UNIT_PRICE FLOAT,
  DISCOUNT_PCT FLOAT,
  TOTAL_AMOUNT FLOAT,
  PAYMENT_METHOD STRING,
  ORDER_STATUS STRING,
  GROSS_AMOUNT FLOAT,
  DISCOUNT_AMOUNT FLOAT,
  NET_AMOUNT FLOAT
);

-- Monthly summary table
CREATE OR REPLACE TABLE MONTHLY_SALES_SUMMARY (
  ORDER_MONTH STRING,
  CATEGORY STRING,
  TOTAL_ORDERS NUMBER,
  TOTAL_UNITS_SOLD NUMBER,
  GROSS_REVENUE FLOAT,
  TOTAL_DISCOUNT FLOAT,
  NET_REVENUE FLOAT,
  AVG_ORDER_VALUE FLOAT
);

-- COPY curated Parquet exports from S3 into Snowflake tables
COPY INTO ORDERS_CURATED
FROM @CURATED_S3_STAGE/orders/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\\.parquet'
ON_ERROR = 'SKIP_FILE';

COPY INTO PRODUCTS_CURATED
FROM @CURATED_S3_STAGE/products/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\\.parquet'
ON_ERROR = 'SKIP_FILE';

COPY INTO CUSTOMERS_CURATED
FROM @CURATED_S3_STAGE/customers/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\\.parquet'
ON_ERROR = 'SKIP_FILE';

COPY INTO SALES_ENRICHED
FROM @CURATED_S3_STAGE/sales_enriched/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\\.parquet'
ON_ERROR = 'SKIP_FILE';

COPY INTO MONTHLY_SALES_SUMMARY
FROM @CURATED_S3_STAGE/monthly_sales_summary/
FILE_FORMAT = (FORMAT_NAME = PARQUET_FF)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*\\.parquet'
ON_ERROR = 'SKIP_FILE';
